package test.exceptions;

import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;

public class UsernameAlreadyExistsExceptionTest {

    @Before
    public void setUp() throws Exception {
    }

    @Test
    public void getUsername() {
    }
}